
CoreTaunts = {} // DO NOT EDIT THIS BRO

CoreTaunts.Custom = false // false = using standart

if CoreTaunts.Custom then // DO NOT EDIT THIS BRO


	CoreTaunts.Compress = true // Using Bz2? YOU CAN EDIT THIS BRO
	
	
	
end // DO NOT EDIT THIS BRO


CoreTaunts.Cooldown = 10 // Eeeh yeah

CoreTaunts.Pitch = 0 // 50 = Darkest monster of your childhood - 255 = MickeyMouse on speed  || 0 = Random ||| Don't go below or higher 

// Gamemode?    0 = Sandbox | 1 = Deathrun by Mr-Gash | 2 = TTT |||| more to come?


CoreTaunts.Gamemode = 1  // This is for Sandbox use CoreTaunts.Team2 to set the sounds up. On TTT Team1 = Traitor


// Just some random sounds out a soundlist https://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/index8f77.html
CoreTaunts.Team1 = {
  "vo/Citadel/al_dienow.wav",
	"vo/Citadel/al_dienow_b.wav",
	"vo/Citadel/al_dontforget.wav",
	"vo/Citadel/al_dontlisten.wav",
	"vo/Citadel/al_dontlistentohim.wav",
	"vo/Citadel/al_doworst.wav",
	"vo/Citadel/al_elevator.wav",
	"vo/Citadel/al_fail_no.wav",
	"vo/Citadel/al_gettingaway.wav",
	"vo/Citadel/al_gogordon.wav",
	"vo/Citadel/al_gordonwouldnever.wav",
	"vo/Citadel/al_heylisten.wav",
	"vo/Citadel/al_hurrymossman02.wav",
	"vo/Citadel/al_itsbreen.wav",
	"vo/Citadel/al_keepgoing.wav",
	"vo/Citadel/al_letyouin.wav",
	"vo/Citadel/al_lookafterdad.wav",
	"vo/Citadel/al_lookafterdad_b.wav",
	"vo/Citadel/al_lookafterdad_c.wav",
	"vo/Citadel/al_lookwhatheleft.wav",
	"vo/Citadel/al_noclue.wav",
	"vo/Citadel/al_notagain02.wav",
	"vo/Citadel/al_notsayinggoodbye.wav",
	"vo/Citadel/al_outofhere.wav",
	"vo/Citadel/al_soldiers01_a.wav",
	"vo/Citadel/al_soldiers01_b.wav",
	"vo/Citadel/al_stayawaycore.wav",
	"vo/Citadel/al_staybackbeam.wav",
	"vo/Citadel/al_struggle01.wav",
	"vo/Citadel/al_struggle02.wav",
	"vo/Citadel/al_struggle03.wav",
	"vo/Citadel/al_struggle05.wav",
	"vo/Citadel/al_struggle07.wav",
	"vo/Citadel/al_struggle08.wav",
	"vo/Citadel/al_success_yes.wav",
	"vo/Citadel/al_success_yes02_nr.wav",
	"vo/Citadel/al_success_yes_nr.wav",
	"vo/Citadel/al_thatshim.wav",
	"vo/Citadel/al_thegravgun01.wav",
	"vo/Citadel/al_thegravgun03.wav",
	"vo/Citadel/al_thegravgun04.wav",
	"vo/Citadel/al_thereheis.wav",
	"vo/Citadel/al_uptop.wav",
	"vo/Citadel/al_watchout01.wav",
	"vo/Citadel/al_wonderwhere.wav",
	"vo/Citadel/al_working.wav",
	"vo/Citadel/al_yes.wav",
	"vo/Citadel/al_yes_nr.wav",
	"vo/Citadel/br_betrayed.wav",
	"vo/Citadel/br_bidder_a.wav",
	"vo/Citadel/br_bidder_b.wav",
	"vo/Citadel/br_circum.wav",
	"vo/Citadel/br_create.wav",
	"vo/Citadel/br_deliver.wav",
	"vo/Citadel/br_dictate_a.wav",
	"vo/Citadel/br_failing11.wav",
	"vo/Citadel/br_farside.wav",
	"vo/Citadel/br_foundation.wav",
	"vo/Citadel/br_freemanatlast.wav",
	"vo/Citadel/br_gift_a.wav",
	"vo/Citadel/br_gift_b.wav",
	"vo/Citadel/br_gift_c.wav",
	"vo/Citadel/br_goback.wav",
	"vo/Citadel/br_gravgun.wav",
	"vo/Citadel/br_guards.wav",
	"vo/Citadel/br_guest_a.wav",
	"vo/Citadel/br_guest_b.wav",
	"vo/Citadel/br_guest_c.wav",
	"vo/Citadel/br_guest_d.wav",
	"vo/Citadel/br_guest_f.wav",
	"vo/Citadel/br_hostbody.wav",
	"vo/Citadel/br_judithwhat.wav",
	"vo/Citadel/br_justhurry.wav",
	"vo/Citadel/br_laugh01.wav",
	"vo/Citadel/br_mentors.wav",
	"vo/Citadel/br_mock01.wav",
	"vo/Citadel/br_mock04.wav",
	"vo/Citadel/br_mock05.wav",
	"vo/Citadel/br_mock06.wav",
	"vo/Citadel/br_mock07.wav",
	"vo/Citadel/br_mock09.wav",
	"vo/Citadel/br_mock13.wav",
	"vo/Citadel/br_newleader_a.wav",
	"vo/Citadel/br_newleader_b.wav",
	"vo/Citadel/br_newleader_c.wav",
	"vo/Citadel/br_no.wav",
	"vo/Citadel/br_nopoint.wav",
	"vo/Citadel/br_nothingtosay_a.wav",
	"vo/Citadel/br_nothingtosay_b.wav",
	"vo/Citadel/br_oheli07.wav",
	"vo/Citadel/br_oheli08.wav",
	"vo/Citadel/br_oheli09.wav",
	"vo/Citadel/br_ohshit.wav",
	"vo/Citadel/br_playgame_a.wav",
	"vo/Citadel/br_playgame_b.wav",
	"vo/Citadel/br_playgame_c.wav",
	"vo/Citadel/br_rabble_a.wav",
	"vo/Citadel/br_rabble_b.wav",
	"vo/Citadel/br_rabble_c.wav",
	"vo/Citadel/br_rabble_d.wav",
	"vo/Citadel/br_stubborn.wav"
}


CoreTaunts.Team2 = {
	"vo/Citadel/al_dienow.wav",
	"vo/Citadel/al_dienow_b.wav",
	"vo/Citadel/al_dontforget.wav",
	"vo/Citadel/al_dontlisten.wav",
	"vo/Citadel/al_dontlistentohim.wav",
	"vo/Citadel/al_doworst.wav",
	"vo/Citadel/al_elevator.wav",
	"vo/Citadel/al_fail_no.wav",
	"vo/Citadel/al_gettingaway.wav",
	"vo/Citadel/al_gogordon.wav",
	"vo/Citadel/al_gordonwouldnever.wav",
	"vo/Citadel/al_heylisten.wav",
	"vo/Citadel/al_hurrymossman02.wav",
	"vo/Citadel/al_itsbreen.wav",
	"vo/Citadel/al_keepgoing.wav",
	"vo/Citadel/al_letyouin.wav",
	"vo/Citadel/al_lookafterdad.wav",
	"vo/Citadel/al_lookafterdad_b.wav",
	"vo/Citadel/al_lookafterdad_c.wav",
	"vo/Citadel/al_lookwhatheleft.wav",
	"vo/Citadel/al_noclue.wav",
	"vo/Citadel/al_notagain02.wav",
	"vo/Citadel/al_notsayinggoodbye.wav",
	"vo/Citadel/al_outofhere.wav",
	"vo/Citadel/al_soldiers01_a.wav",
	"vo/Citadel/al_soldiers01_b.wav",
	"vo/Citadel/al_stayawaycore.wav",
	"vo/Citadel/al_staybackbeam.wav",
	"vo/Citadel/al_struggle01.wav",
	"vo/Citadel/al_struggle02.wav",
	"vo/Citadel/al_struggle03.wav",
	"vo/Citadel/al_struggle05.wav",
	"vo/Citadel/al_struggle07.wav",
	"vo/Citadel/al_struggle08.wav",
	"vo/Citadel/al_success_yes.wav",
	"vo/Citadel/al_success_yes02_nr.wav",
	"vo/Citadel/al_success_yes_nr.wav",
	"vo/Citadel/al_thatshim.wav",
	"vo/Citadel/al_thegravgun01.wav",
	"vo/Citadel/al_thegravgun03.wav",
	"vo/Citadel/al_thegravgun04.wav",
	"vo/Citadel/al_thereheis.wav",
	"vo/Citadel/al_uptop.wav",
	"vo/Citadel/al_watchout01.wav",
	"vo/Citadel/al_wonderwhere.wav",
	"vo/Citadel/al_working.wav",
	"vo/Citadel/al_yes.wav",
	"vo/Citadel/al_yes_nr.wav",
	"vo/Citadel/br_betrayed.wav",
	"vo/Citadel/br_bidder_a.wav",
	"vo/Citadel/br_bidder_b.wav",
	"vo/Citadel/br_circum.wav",
	"vo/Citadel/br_create.wav",
	"vo/Citadel/br_deliver.wav",
	"vo/Citadel/br_dictate_a.wav",
	"vo/Citadel/br_failing11.wav",
	"vo/Citadel/br_farside.wav",
	"vo/Citadel/br_foundation.wav",
	"vo/Citadel/br_freemanatlast.wav",
	"vo/Citadel/br_gift_a.wav",
	"vo/Citadel/br_gift_b.wav",
	"vo/Citadel/br_gift_c.wav",
	"vo/Citadel/br_goback.wav",
	"vo/Citadel/br_gravgun.wav",
	"vo/Citadel/br_guards.wav",
	"vo/Citadel/br_guest_a.wav",
	"vo/Citadel/br_guest_b.wav",
	"vo/Citadel/br_guest_c.wav",
	"vo/Citadel/br_guest_d.wav",
	"vo/Citadel/br_guest_f.wav",
	"vo/Citadel/br_hostbody.wav",
	"vo/Citadel/br_judithwhat.wav",
	"vo/Citadel/br_justhurry.wav",
	"vo/Citadel/br_laugh01.wav",
	"vo/Citadel/br_mentors.wav",
	"vo/Citadel/br_mock01.wav",
	"vo/Citadel/br_mock04.wav",
	"vo/Citadel/br_mock05.wav",
	"vo/Citadel/br_mock06.wav",
	"vo/Citadel/br_mock07.wav",
	"vo/Citadel/br_mock09.wav",
	"vo/Citadel/br_mock13.wav",
	"vo/Citadel/br_newleader_a.wav",
	"vo/Citadel/br_newleader_b.wav",
	"vo/Citadel/br_newleader_c.wav",
	"vo/Citadel/br_no.wav",
	"vo/Citadel/br_nopoint.wav",
	"vo/Citadel/br_nothingtosay_a.wav",
	"vo/Citadel/br_nothingtosay_b.wav",
	"vo/Citadel/br_oheli07.wav",
	"vo/Citadel/br_oheli08.wav",
	"vo/Citadel/br_oheli09.wav",
	"vo/Citadel/br_ohshit.wav",
	"vo/Citadel/br_playgame_a.wav",
	"vo/Citadel/br_playgame_b.wav",
	"vo/Citadel/br_playgame_c.wav",
	"vo/Citadel/br_rabble_a.wav",
	"vo/Citadel/br_rabble_b.wav",
	"vo/Citadel/br_rabble_c.wav",
	"vo/Citadel/br_rabble_d.wav",
	"vo/Citadel/br_stubborn.wav"
}

 // https://wiki.garrysmod.com/page/Enums/ACT keep experimenting with it though
CoreTaunts.Acts = {
	ACT_GMOD_GESTURE_TAUNT_ZOMBIE,
	ACT_GMOD_GESTURE_WAVE,
	ACT_GMOD_TAUNT_CHEER,
	ACT_GMOD_TAUNT_DANCE,
	ACT_GMOD_TAUNT_LAUGH,
	ACT_GMOD_TAUNT_MUSCLE,
	ACT_GMOD_TAUNT_PERSISTENCE,
	ACT_GMOD_TAUNT_ROBOT,
	ACT_GMOD_TAUNT_SALUTE
} 


